### ISSUE TITLE
Failed to download errors inside DDEV container in Github Actions

### ISSUE THREAD

**Issue by davereid-pfg** [jonaseberle/github-action-setup-ddev#17]
I'm encountering a bunch of random download errors from my Github Actions when ddev starts up with this action:

One build failed on composer install:
```
Loading composer repositories with package information
https://repo.packagist.org/ could not be fully loaded (curl error 28 while downloading https://repo.packagist.org/p2/psr/event-dispatcher.json: Failed to connect to repo.packagist.org port 443: Connection timed out), package information was loaded from the local cache and may be out of date

In CurlDownloader.php line 377:
                                                                               
  curl error 28 while downloading https://repo.packagist.org/p2/phpdocumentor  
  /reflection-common.json: Failed to connect to repo.packagist.org port 443:   
  Connection timed out
```

Another build failed on downloading mutagen:
```
Failed to start SITENAME: download link https://github.com/mutagen-io/mutagen/releases/download/v0.14.0/mutagen_linux_amd64_v0.14.0.tar.gz returned wrong status code: got 503 want 200
```

I'm not sure what's up or if I've been rate limited somehow.

**Comment by rfay** [comment]
Most likely random network/github errors. Do you get it when you retry?

**Comment by davereid-pfg** [comment]
This was on two different runs, but it looks like it's been resolved now. Github status wasn't showing any issues with runners.

**Comment by rfay** [comment]
Github actually has lots of random troubles. Your 503 looked like a  temporary problem with repo.packagist.org

Github has lots of troubles, as does the internet in general :)
