### ISSUE TITLE
allow to change PHP version in .ddev/config.yaml

### ISSUE THREAD

**Issue by jonaseberle** [jonaseberle/github-action-setup-ddev#2]
This could be done like this:
    # Set PHP version
    sed -i -e 's/^php_version:.*/php_version: ${{ matrix.php-version }}/g' .ddev/config.yaml

This would enable matrix-builds with PHP versions.

**Comment by jonaseberle** [comment]
A workaround is to just put this in your workflow:

```
        strategy:
            fail-fast: false
            matrix:
                php-version: [7.2, 7.3]
        steps:
            -   uses: actions/checkout@v1
            # Set PHP version
            -   run: |
                    sed -i -e 's/^php_version:.*/php_version: ${{ matrix.php-version }}/g' .ddev/config.yaml
            # Start ddev
            -   uses: jonaseberle/github-action-setup-ddev@v1
```

**Comment by rfay** [comment]
Actually, if you just leave the php version out of the config.yaml, it will use ddev's default PHP, which might be better? Currently 7.3, in 1.7 will change to 7.4.  But still people will need to change it.

**Comment by jonaseberle** [comment]
@rfay I thought this could be handy for matrix-tests against different PHP versions. 

Currently ddev uses what it finds in the project's (not this, this is just for the tests of the action!) `.ddev/config.yaml`.

I'll close this as the workaround is actually not a workaround but pretty clean ;)
