### ISSUE TITLE
Maintainers, ownership, promotion to ddev namespace?

### ISSUE THREAD

**Issue by rfay** [jonaseberle/github-action-setup-ddev#25]
Thanks for making me owner and getting @davereid-pfg  in there, it's a good idea. In fact it might be a good idea to promote this to ddev workspace. I won't be doing anything to it since I don't personally use it, but for the overall stability and future of the repo it's good to have responsible owners.

Would you be up for promoting it to ddev? Github is quite good about redirects, I imagine Github Actions is as well...

**Comment by davereid-pfg** [comment]
Not sure about Github Actions redirecting to the correct one, likely we'd need to update existing references, but I'm not 100% certain on that.

+1 to moving under the drud workspace!

**Comment by rfay** [comment]
I definitely wouldn't want to break anybody. It's easy to test though. Create a different github action, use it somewhere, move it, see if the action still works. If that doesn't work, we could move it, then fork again into jonaseberle, but I don't like that idea at all.

**Comment by davereid-pfg** [comment]
According to https://github.com/github/docs/issues/15575 we should probably just create a new repository and archive the old one.

**Comment by davereid-pfg** [comment]
> Note: GitHub will not redirect calls to an action hosted by a renamed repository. Any workflow that uses that action will fail with the error repository not found. Instead, create a new repository and action with the new name and archive the old repository. For more information, see "[Archiving repositories](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)."

https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by rfay** [comment]
It's easy to fork it into drud/gitub-action-setup-ddev, easy then to archive old one. Requires github's intervention to unfork the drud/github-action-setup-ddev then, but they've been responsive in the past.

**Comment by rfay** [comment]
Regardless, this whole idea is completely at your discretion @jonaseberle .

**Comment by jonaseberle** [comment]
From an experiment with some necessary workarounds for the reverse proxy this has become pretty trivial and easy to maintain :) So yes, I am happy and feel honored to have it "official"ized. It is so amazing how many platforms DDEV is officially supporting!

What holds me back a bit:
The code is more ugly than it needs to be currently. What we have now has been compiled from TypeScript once and smells. It's easy enough to clean it up, though and I can take care of that soonish.


If I understand correctly we could just `push` it into a new `drud/github-action-setup-ddev` remote? 
So IMHO no fork would be necessary.
```
git remote remove origin
git remote add origin git@github.com:drud/github-action-setup-ddev.git
git push [origin master]
```
After that we could push one last README-change here ("We have moved - please use ...") and archive it.


I'll be away from any developer computer for the next week and on holidays in Belgium :)

**Comment by rfay** [comment]
Let's put it on hold until you're back and want to go forward of course.

**Comment by heddn** [comment]
bump

**Comment by rfay** [comment]
It's easy to do this... It will work without any problems because Github does a good job on redirects. Retitling to "ddev" namespace.

**Comment by davereid** [comment]
Can I request to remove @davereid-pfg and add my regular account @davereid as a maintainer? We had some internal changes with enterprise Github and I'm no longer using that account.

**Comment by davereid-pfg** [comment]
Just checking in with the old account as well, I approve adding my regular account as a maintainer before I close this one.

**Comment by jonaseberle** [comment]
@davereid I've added your new identity ;)

I've still not removed the code smell but never mind. 

Shall I go ahead and use this to transfer to the `ddev` org?
![image](https://user-images.githubusercontent.com/1678001/227937582-3b333c07-28c8-4cd8-880c-345a293b3d51.png)

Or would you @rfay rather add a new repository and we do
```
git remote remove origin
git remote add origin git@github.com:ddev/github-action-setup-ddev.git
git push [origin master]
```

**Comment by rfay** [comment]
I think I have to do it; also note that github will handle redirects ok of existing remotes, but it will pester you enough that you sort it out. 

@jonaseberle if you're ready to transfer this to the ddev namespace (and keep maintaining it of course) make me an owner if you can. If you can't, I'll give you temporary privileges on the ddev org. Let me know when you're ready. I'm traveling today so may not be available all the time.

**Comment by davereid** [comment]
FYI I don't think we should transfer as per https://github.com/jonaseberle/github-action-setup-ddev/issues/25#issuecomment-1206747438 - we would break existing action usages.

**Comment by rfay** [comment]
Sorry, missed that. I'm surprised. They do everything else so well.

**Comment by rfay** [comment]
Invited you both to https://github.com/ddev/github-action-setup-ddev - if you prefer to rename or etc before publicizing, that's fine too.

**Comment by jonaseberle** [comment]
I would stay with `ddev/github-action-setup-ddev` if that's fine for all.

**Comment by davereid** [comment]
@rfay Can you resend the invite to me? It expired. :/

I'm okay with the name as well.

**Comment by rfay** [comment]
Invited.

**Comment by davereid** [comment]
Should I go ahead and mirror all the existing Git code to the new repository?

**Comment by rfay** [comment]
I think that was the agreement with everybody.

**Comment by jonaseberle** [comment]
Yes, that sounds great to me.

**Comment by davereid** [comment]
Code has been mirrored over to https://github.com/[ddev/github-action-setup-ddev](https://github.com/ddev/github-action-setup-ddev). I started enabling some branch protection, updating references, enabling Dependabot, etc. I think we can mark this as archived once we get a new release out there, but all the same tags exist there as well so people should be able to switch over seamlessly.

**Comment by davereid** [comment]
Going to leave this open until archiving is done.

**Comment by jonaseberle** [comment]
I am going to tag a new release v1.8.0 (minor version raise) in the new repo so that people can start using it.

**Comment by jonaseberle** [comment]
I think nothing will break if we archive now.
It will unpublish the action from the Marketplace but that is a good thing so we can publish it again from the new repo.

Thanks all! Sorry that I have been so unresponsive.

**Comment by davereid** [comment]
@jonaseberle I think we might need an updated release on this repo with the name rename first.

**Comment by jonaseberle** [comment]
Ah, I see. I released a [v1.7.2](https://github.com/jonaseberle/github-action-setup-ddev/releases/tag/v1.7.2). 
The first one in the new repo is v1.8.0.

**Comment by jonaseberle** [comment]
I discovered the "unpublish from Marketplace" button in this one but I can't publish the new one yet.

https://github.com/ddev/github-action-setup-ddev/releases/edit/v1.8.0 :
![image](https://user-images.githubusercontent.com/1678001/234797802-5528c1d3-2ca0-4ed7-adb0-eb8bf57ed1cd.png)

I think we can figure that out later. It's really just a marketing thing - any Github repo with an `action.yaml` can be used as action.

**Comment by jonaseberle** [comment]
It still moans about that name "Setup DDEV" already taken. Any ideas for a new one?

**Comment by jonaseberle** [comment]
I have gotten a clue why I might not have been able to publish the new one.

From
https://docs.github.com/en/enterprise-cloud@latest/actions/creating-actions/publishing-actions-in-github-marketplace

> The name cannot match a user or organization on GitHub, unless the user or organization owner is publishing the action. For example, only the GitHub organization can publish an action named github.

Could an organisation owner @rfay try to set that checkmark?
![image](https://github.com/jonaseberle/github-action-setup-ddev/assets/1678001/7740486d-8089-4726-9ae1-13d6ad50d204)
https://github.com/ddev/github-action-setup-ddev/releases/edit/v1.8.0

**Comment by rfay** [comment]
Here's what I get:

<img width="1031" alt="image" src="https://github.com/jonaseberle/github-action-setup-ddev/assets/112444/1403f4c3-c1d9-4755-8b69-21e53a5b9e9a">

**Comment by jonaseberle** [comment]
Ok, thanks for trying. 
Let's call it "Setup DDEV in Github Workflows" then. I'll push a change.

**Comment by jonaseberle** [comment]
Heureka! 
https://github.com/marketplace/actions/setup-ddev-in-github-workflows

I'll finally archive this repo now to get people to move over.
