### ISSUE TITLE
Support installing when action runner is macos-latest

### ISSUE THREAD

**Issue by davereid-pfg** [jonaseberle/github-action-setup-ddev#27]
I would like to be able to use this action to install DDEV on a Mac-based workflow for some regression testing, but it only supports Linux runners currently.

**Comment by rfay** [comment]
Mac is really hard. There's no command-line way to start Docker Desktop if you want it. You can do Colima, as DDEV has colima tests. But I was never able to get mkcert installed without access to the UI, so had to use http for everything.

**Comment by jonaseberle** [comment]
I am interested to know what the Mac-based workflow looks like. Are you using host commands that are specific to Mac?

**Comment by davereid-pfg** [comment]
Yeah I kind of figured we would use brew to install colima ourselves before running this.

**Comment by jonaseberle** [comment]
Hey, we have moved to https://github.com/ddev/github-action-setup-ddev.
This repo will be archived (read-only). I am going to close all issues. Please feel free to open a new one in the new place if you think it makes sense.
