### ISSUE TITLE
Integration with codespaces?

### ISSUE THREAD

**Issue by ethanteague** [jonaseberle/github-action-setup-ddev#34]
Wondering if it would be possible to use this with prebuilds? I'm running ddev in codespaces with a custom devcontainer.json file. For the life of me, I can't get the codespace secrets into the container.

**Comment by rfay** [comment]
This is a GitHub Action, AFAIK it's not related to anything you'd do with a devcontainer, but interested in learning...

But I don't think you'd ever want secrets in a container would you? Then they wouldn't be secrets? Maybe I don't understand. But I would appreciate if you could try out the new explicit codespaces feature in DDEV, https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#github-codespaces

**Comment by ethanteague** [comment]
Howdy, @rfay! I'm trying to replicate my live site in a codespace in a private repo. To that end, I need to pull in a db from a prod dump on acquia cloud to match live data. I have my key stored as a secret in codespaces secrets, and up until a couple of weeks ago, I was able to add my secret in a devcontainer.json `onCreateCommand` hook script to a ddev instance in codespaces like so:
```
ddev exec eval `ssh-agent`
# Add our key.
ddev exec ssh-add - <<< echo ${ID_RSA}
ddev restart
```

This allowed me to do a drush sql-sync from acquia into my prebuilds. This stopped working a couple of weeks ago, and I haven't been able to figure out a way to get my key back in the container so that I don't get perm errors when trying to pull in my db. 

Anyways, the secret isn't making it into the container now, and that's what I'm trying to figure out.

EDIT: forget to mention, I did mirror your devcontainer setup, here: https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#github-codespaces

**Comment by rfay** [comment]
I'm really surprised you were able to do that in the first place, as `ssh-add` requires a tty. I've always had to do that sort of thing with expect like this, 

https://github.com/drud/ddev/blob/b0ba7ff9086b4cb107c3251cba8a1134794ef90d/pkg/ddevapp/testdata/TestAcquiaPull/ddevauthssh.expect

But of course... if you can't get the secret into the container at all any more, then that's something for GitHub support. I recommend experimenting with a trivial secret that doesn't need something as complex as ssh management, and see if you're getting any secrets in there.

BTW, your initial 
```
ddev exec eval `ssh-agent`
```

Looks quite strange to me. That says "Run ddev exec eval <whatever the results of ssh-agent were on the host>" - What do you think is the intent of that? (I would also recommend using the more modern `ddev exec eval $(ssh-agent)` if that's what you're intending to do.)

I guess I'd expect you to use `ddev auth ssh` in this context, perhaps you're doing something that is intended to result in the same behavior. The expect approach would work with that, if you can get the secret in there.

**Comment by ethanteague** [comment]
I found that if I didn't run ```ddev exec eval `ssh-agent` ``` I couldn't do `ddev exec ssh-add - <<< echo ${ID_RSA}` - I would get messages that the ssh agent had to be turned on - guess it's just a hacky way of turning it on (thanks for the `ddev exec eval $(ssh-agent)` tip!).

I did try writing out my secret to a file, and then running `ddev auth ssh` initially, but ran into issues with the way I was writing it out resulting in errors relating to my key being improperly formatted.

**Comment by rfay** [comment]
Right, the you aren't doing there what you intend. You would be wanting to do something like `ddev exec 'eval $(ssh-agent)'` to accomplish running the ssh-agent inside the web container. (Note that normally the ssh agent runs inside the ssh-agent container (and is already running) when you use `ddev auth ssh`)

**Comment by jonaseberle** [comment]
I understand you are not using this Github action but you want to do something we mentioned in the README in another context?
Of course you are welcome to ask here, but I do not understand why you do not do it as we suggest in the README?

Just putting the whole SSH-setup into `.ddev/homeadditions/.ssh/` is really what I believe the best portable way (no sane TTY or console or potentially complicated preserving of environment variables is necessary) to do it.
https://github.com/jonaseberle/github-action-setup-ddev#ssh-keys

You can also run an ssh-agent outside of ddev, insert the keys there and `ddev auth ssh` but that is just more complicated and achieves the same. The solution we propose here does not even need any ssh-agent! That's just pure SSH using a default private key location (`~/.ssh/id_rsa`).

That said, I have never tried codespaces ;)

**Comment by jonaseberle** [comment]
Hey, we have moved to https://github.com/ddev/github-action-setup-ddev.
This repo will be archived (read-only). I am going to close all issues. Please feel free to open a new one in the new place if you think it makes sense.
