### ISSUE TITLE
Consider moving to drud (soon to be ddev) org

### ISSUE THREAD

**Issue by rfay** [jonaseberle/github-action-setup-ddev#35]
@jonaseberle this seems to be a very successful and useful project. Would you consider maintaining it in the drud org (soon to be ddev org) where it would be easier to find? It's easy to move it.

**Comment by jonaseberle** [comment]
Yes. 
Continuing from https://github.com/jonaseberle/github-action-setup-ddev/issues/25 I've not cleaned it up yet but I believe that's not holding us back.

**Comment by rfay** [comment]
Sorry I didn't remember #25 :) Any time you'd like to do this say the word and we can do it.

**Comment by rfay** [comment]
Closing as duplicate of #25
