### ISSUE TITLE
Starting ddev fails with Error: 1

### ISSUE THREAD

**Issue by nostadt** [jonaseberle/github-action-setup-ddev#5]
```
ddev-router is up-to-date

Failed to start project: ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=, err=health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=

Error: 1
```

See #4 for my GitHub workflow.

-----------------------
It seems the previous fix for nginx-router
jwilder/docker-gen#315
https://github.com/jonaseberle/github-action-setup-ddev/blob/master/.ddev/patches/ddev-router/nginx.tmpl
does not do its job any more.

**Comment by rfay** [comment]
One mention on this: ddev v1.16 includes the ability to use a ~/.ddev/router-compose.*.yaml to override facets of the compose setup. So it would be possible to override the healthcheck if that's the issue.

**Comment by nostadt** [comment]
Interesting. @jonaseberle 
Could this be sth.?

**Comment by rfay** [comment]
This same problem is blocking move of ddev to github actions. I'll try to learn enough to debug this this week.

**Comment by rfay** [comment]
The first thing that I note is that https://github.com/jonaseberle/github-action-setup-ddev/blob/master/.ddev/patches/ddev-router/nginx.tmpl really couldn't work with ddev v1.16+ because nginx.tmpl changed quite a bit. So we might be able to fix it just with a new file; it would probably be better implemented as a patch so that ddev changes didn't make it incompatible. 

But it would really be nice to get to the bottom of the underlying problem while we're here.

**Comment by rfay** [comment]
It looks to me like the nginx.tmpl provided here (https://github.com/jonaseberle/github-action-setup-ddev/blob/master/.ddev/patches/ddev-router/nginx.tmpl) was already long out of date before v1.16 came out. I'm trying to figure out its actual derivation, and don't see the original issue which would have explored this. I do see the docker-gen issue, https://github.com/jwilder/docker-gen/issues/315, but don't see context on how the nginx.tmpl works around that. 

The diff from ddev v1.15.3 nginx to nginx.tmpl here is https://gist.github.com/rfay/86aefe5c6555b4e41009541aa171355b

**Comment by rfay** [comment]
It looks like github-action-setup-ddev was born in Nov 2019; the nginx.tmpl here went in on the first commit. That suggests it might have matched the nginx.tmpl from ddev v1.11.2, from Oct 8, 2019. The diff from ddev v1.11.2 version of nginx.tmpl is at https://gist.github.com/rfay/48f10f0dba32af08428d8267e5f07992

**Comment by rfay** [comment]
I'm working on this and having some success. Hopefully I'll be able to do a PR soon.

**Comment by rfay** [comment]
#6 is passing tests!

**Comment by nostadt** [comment]
Hey @rfay 
I just want to leave a big thank you here! I highly appreciate your time and fix 😃

**Comment by rfay** [comment]
You're welcome @AMartinNo1 ! Yay for @jonaseberle for pioneering and maintaining this technique. 

Next step is we'll figure out how not to have to overwrite the nginx.tmpl and why that problem happens.
