### ISSUE TITLE
Question: Is it possible to have the .ddev located outside the root dir?

### ISSUE THREAD

**Issue by tomasnorre** [jonaseberle/github-action-setup-ddev#8]
Hi,

I'm about to move the CI for the TYPO3 Crawler to Github Actions. Currently they are running in travis, with DDEV and CodeCeption for tests.

This action (yours) expect as I see it that the `.ddev` folder is located in the repository root, but for the crawler it's in `.devbox` as I have other things include like db-backup, different composer.json etc. 

Long story short,
Is it's possible to have .ddev outside of the repository root?

**Comment by tomasnorre** [comment]
From this https://github.com/jonaseberle/github-action-setup-ddev/blob/master/lib/main.js#L56 it doesn't look like it's possible atm. 
Would it be an option that you would consider to add?

**Comment by jonaseberle** [comment]
Hi Tomas,
It shouldn't be too hard to add an option to the action and change directory before `ddev start`.
I wouldn't oppose it ;)

**Comment by tomasnorre** [comment]
I'm not really familier with how to do this, but I could give it a spin. 

My suggestion would be. 

Keep as is, if no "ddevDir" is set in environment variables?

**Comment by jonaseberle** [comment]
I would rather go for an option for the Github action.

Like

    - uses: jonaseberle/github-action-setup-ddev@v1
      ddevDir: someDir/subdir/subdir  # default: .

If you don't need it right now, I'll do it in the next weeks.

**Comment by tomasnorre** [comment]
Sounds great. Thanks.

**Comment by tomasnorre** [comment]
I've been looking into this multiple times, but I cannot get my head around have to add this. Can you give me some pointers, then I would be happy to do a PR.

**Comment by jonaseberle** [comment]
Hi @tomasnorre, that would be great. 

I would have started with adding parameters (aka `inputs`) https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions for the action.

Then we use them in our action code https://github.com/jonaseberle/github-action-setup-ddev/blob/master/lib/main.js

**Comment by tomasnorre** [comment]
Thanks for the pointer. I will have a look at it.
